[package]
name = "fantastic-garbanzo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"
futures = "0.3.25"
async-std = "1.12.0"